### ISSUE TITLE
Inferred version is SNAPSHOT just after release task execution

### ISSUE THREAD

**Issue by rzabini** [tschulte/gradle-semantic-release-plugin#5]
Hi, thank you for the nice work on this plugin.
Consider this case: I just successfully ran the _release_ task, so the repository has been tagged with the new semver version (say it's 1.1.0).
Now I want to publish the artifact to another repository, using the inferred version: what I get is 1.1.1-SNAPSHOT. I would expect the inferred version to be still 1.1.0, as the working directory is clean, and HEAD is on tag 1.1.0: am I wrong?

Thank you,
Romano

**Comment by tschulte** [comment]
Yes, I have also considered adding this, but wanted to finally release version 1.0.0, since this can be added later. 

When using the proposed workflow, the CI server does always use the `release` task. Only when there are relevant changes and the branch is e.g. master, a tag is created. The plugin itself does not do more. Only when using `tasks.release.dependsOn` and `tasks.release.finalizedBy` the CI server will do more, e.g. build the jars and publish them to some maven repo.

Now, pushing the tag and publishing the jar are not atomic, i.e. it is possible that the tag can be pushed but the version can not be published due to a server outage or because the CI server was misconfigured. In this case such a feature would be really nice. Currently the only option is to either delete the tag and try again or to create a new release and skip the version (having a tag without a maven artefact.

Adding this behaviour to the plugin is easy. It can be done without changing the plugin by you in your `build.gradle`, by the way:

``` gradle
release {
    versionStrategy org.ajoberstar.gradle.git.release.semver.RebuildVersionStrategy.INSTANCE
}
```

The problem however is that you must ensure that your publish task does not fail when rebuilding. Let's have a look at an example:

``` gradle
plugins {
    id 'de.gliderpilot.semantic-release' version '1.1.1'
}
apply plugin: 'java'
apply plugin: 'maven-publish'

group = 'org.example'

release {
    versionStrategy org.ajoberstar.gradle.git.release.semver.RebuildVersionStrategy.INSTANCE
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven {
            url "http://nexus.example.org/${version.toString().endsWith('-SNAPSHOT') ? 'snapshots' : 'releases'}"
        }
    }
}

tasks.release {
    dependsOn build
    finalizedBy publish
}
```

What does the above do? This is a java project, when calling the `release` task, either a real release is performed with creating a tag and uploading to repo `releases` on nexus, or only a SNAPSHOT is uploaded to repo `snapshots` on nexus. Uploading several SNAPSHOTS to nexus is no problem. But the `releases` repo is most probably configured to not allow publishing of the same artefacts more than once. And here it hits the fan. The second time you call `gradle release` the build will most likely fail, because nexus will reject publishing the artefacts again.

**Comment by rzabini** [comment]
Thank you for the thorough explanation, it makes sense.
The solution you suggest, adding the _RebuildVersionStrategy_ to the _release_ configuration solves my problem, so I am closing the issue.
